### ISSUE TITLE
Segfault when using --list-tests

### ISSUE THREAD

**Issue by landersson** [catchorg/Catch2#1534]
**Describe the bug**
I'm getting a segfault when trying to use the -l option to list tests:
```
leeloo:build:>./projects/SelfTest
loose text artifact
===============================================================================
All tests passed (1128 assertions in 178 test cases)
leeloo:build:>lldb projects/SelfTest -- -l
(lldb) target create "projects/SelfTest"
Current executable set to 'projects/SelfTest' (x86_64).
(lldb) settings set -- target.run-args  "-l"
(lldb) r
Process 40821 launched: '/Users/larsandersson/dev/Catch2/build/projects/SelfTest' (x86_64)
All available test cases:
Process 40821 stopped
* thread #1: tid = 0x51476e, 0x00000001001b5e29 SelfTest`Catch::(anonymous namespace)::PosixColourImpl::setColour(this=0x00000001002fd000, _escapeCode="[0m") + 41 at catch_console_colour.cpp:163, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001001b5e29 SelfTest`Catch::(anonymous namespace)::PosixColourImpl::setColour(this=0x00000001002fd000, _escapeCode="[0m") + 41 at catch_console_colour.cpp:163
   160
   161      private:
   162          void setColour( const char* _escapeCode ) {
-> 163              getCurrentContext().getConfig()->stream()
   164                  << '\033' << _escapeCode;
   165          }
   166      };
```

**Expected behavior**
No segfault, tests listed.

**Reproduction steps**
Build on Mac OS X and try to list the tests in the SelfTest binary. Happy to provide more info/context if this turns out to be hard to reproduce.

**Platform information:**

 - OS: Mac OS X 10.11.6 (El Capitan)
 - Compiler+version: Apple LLVM version 8.0.0 (clang-800.0.42.1), g++-7
 - Catch version: git master and 2.6.0 

**Additional context**
Also happens with g++-mp-7 (MacPorts gcc7 7.3.0_3) 7.3.0

**Comment by bartlibert** [comment]
I can confirm this on my system:

OS: Debian GNU/Linux buster
Compiler+version: g++ (Debian 8.2.0-16) 8.2.0
Catch version: 2.6.0

**Comment by JoeyGrajciar** [comment]
Issue found and solved in linked commit.

**Comment by landersson** [comment]
How do I try this fix? I've tried cloning catch2 master, built it, make install and then copy include/catch2/catch.hpp from the resulting install directory into my own repo.

After a complete rebuild of my test executable, I'm still getting a segfault.

**Comment by JoeyGrajciar** [comment]
run
`python scripts/generateSingleHeader.py` 
from root of cloned repo

**Comment by landersson** [comment]
Thanks @JoeyGrajciar , works fine for me now.
